In [1]:
import pandas as pd

In [2]:
dfp = pd.read_csv('data/player_data.csv') 
dfp.tail()

,name,year_start,year_end,position,height,weight,birth_date,college
4545,Ante Zizic,2018,2018,F-C,6-11,250.0,"January 4, 1997",NaN
4546,Jim Zoet,1983,1983,C,7-1,240.0,"December 20, 1953",Kent State University
4547,Bill Zopf,1971,1971,G,6-1,170.0,"June 7, 1948",Duquesne University
4548,Ivica Zubac,2017,2018,C,7-1,265.0,"March 18, 1997",NaN
4549,Matt Zunic,1949,1949,G-F,6-3,195.0,"December 19, 1919",George Washington University

In [3]:
dfs = pd.read_csv('data/Seasons_Stats.csv', index_col = 0)
dfs.tail()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [4]:
players_studied = ['Kevin Durant', 'Dwyane Wade', 'Tim Duncan', 'Allen Iverson', 'Ray Allen', 'Vince Carter', 'Kobe Bryant', 'LeBron James', 'Tracy McGrady', 'Kevin Garnett']
yearInNBA = {}

In [5]:
mydf = dfs[dfs.Player.isin(players_studied)]
mydf.tail()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24057,2016.0,Dwyane Wade,SG,34.0,MIA,74.0,73.0,2258.0,20.3,0.517,...,0.793,82.0,220.0,302.0,344.0,79.0,42.0,203.0,116.0,1409.0
24184,2017.0,Vince Carter,SF,40.0,MEM,73.0,15.0,1799.0,11.7,0.542,...,0.765,36.0,191.0,227.0,133.0,60.0,36.0,50.0,163.0,586.0
24239,2017.0,Kevin Durant,SF,28.0,GSW,62.0,62.0,2070.0,27.6,0.651,...,0.875,39.0,474.0,513.0,300.0,66.0,99.0,138.0,117.0,1555.0
24365,2017.0,LeBron James,SF,32.0,CLE,74.0,74.0,2794.0,27.0,0.619,...,0.674,97.0,543.0,640.0,646.0,92.0,44.0,303.0,134.0,1954.0
24643,2017.0,Dwyane Wade,SG,35.0,CHI,60.0,59.0,1792.0,18.5,0.508,...,0.794,64.0,207.0,271.0,229.0,86.0,41.0,138.0,112.0,1096.0

In [6]:
#dfp[dfp.name.isin(players_studied)].year_start.astype(float)

In [7]:
#values = {}
#for player in players_studied:
#    print(player)
#    print(mydf[mydf.Player == player].Year - float(dfp[dfp.name == player].year_start))

In [8]:
dfs['name'] = dfs['Player']

In [10]:
dfp2 = dfp[['name','height', 'college']]
dfp2.reset_index()

,index,name,height,college
0,0,Alaa Abdelnaby,6-10,Duke University
1,1,Zaid Abdul-Aziz,6-9,Iowa State University
2,2,Kareem Abdul-Jabbar,7-2,"University of California, Los Angeles"
3,3,Mahmoud Abdul-Rauf,6-1,Louisiana State University
4,4,Tariq Abdul-Wahad,6-6,San Jose State University
5,5,Shareef Abdur-Rahim,6-9,University of California
6,6,Tom Abernethy,6-7,Indiana University
7,7,Forest Able,6-3,Western Kentucky University
8,8,John Abramovic,6-3,Salem International University
9,9,Alex Abrines,6-6,NaN
10,10,Alex Acker,6-5,Pepperdine University
11,11,Don Ackerman,6-0,Long Island University
12,12,Mark Acres,6-11,Oral Roberts University
13,13,Bud Acton,6-6,Hillsdale College
14,14,Quincy Acy,6-7,Baylor University
15,15,Alvan Adams,6-9,University of Oklahoma
16,16,Don Adams,6-6,Northwestern University
17,17,George Adams,6-5,Gardner-Webb University
18,18,Hassan Adams,6-4,University of Arizona
19,19,Jordan Adams,6-5,"University of California, Los Angeles"
20,20,Michael Adams,5-10,Boston College
21,21,Steven Adams,7-0,University of Pittsburgh
22,22,Rafael Addison,6-7,Syracuse University
23,23,Bam Adebayo,6-10,University of Kentucky
24,24,Rick Adelman,6-1,Loyola Marymount University
25,25,Jeff Adrien,6-7,University of Connecticut
26,26,Arron Afflalo,6-5,"University of California, Los Angeles"
27,27,Maurice Ager,6-5,Michigan State University
28,28,Mark Aguirre,6-6,DePaul University
29,29,Blake Ahearn,6-2,Missouri State University
...,...,...,...,...
4520,4520,James Young,6-6,University of Kentucky
4521,4521,Joe Young,6-2,University of Oregon
4522,4522,Korleone Young,6-7,NaN
4523,4523,Michael Young,6-7,University of Houston
4524,4524,Nick Young,6-7,University of Southern California
4525,4525,Perry Young,6-5,Virginia Polytechnic Institute and State Unive...
4526,4526,Sam Young,6-6,University of Pittsburgh
4527,4527,Thaddeus Young,6-8,Georgia Institute of Technology
4528,4528,Tim Young,7-0,Stanford University
4529,4529,Sun Yue,6-9,NaN
4530,4530,Max Zaslofsky,6-2,St. John's University
4531,4531,Zeke Zawoluk,6-7,St. John's University
4532,4532,Cody Zeller,7-0,Indiana University
4533,4533,Dave Zeller,6-1,Miami University
4534,4534,Gary Zeller,6-3,Drake University
4535,4535,Harry Zeller,6-4,Washington & Jefferson College
4536,4536,Luke Zeller,6-11,University of Notre Dame
4537,4537,Tyler Zeller,7-0,University of North Carolina
4538,4538,Tony Zeno,6-8,Arizona State University
4539,4539,Phil Zevenbergen,6-10,University of Washington
4540,4540,Wang Zhizhi,7-0,NaN
4541,4541,George Zidek,7-0,"University of California, Los Angeles"
4542,4542,Derrick Zimmerman,6-3,Mississippi State University
4543,4543,Stephen Zimmerman,7-0,"University of Nevada, Las Vegas"
4544,4544,Paul Zipser,6-8,NaN
4545,4545,Ante Zizic,6-11,NaN
4546,4546,Jim Zoet,7-1,Kent State University
4547,4547,Bill Zopf,6-1,Duquesne University
4548,4548,Ivica Zubac,7-1,NaN
4549,4549,Matt Zunic,6-3,George Washington University

In [11]:
df_merge = dfs.set_index('name').join(dfp.set_index('name'))

In [12]:
df_merge.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,TOV,PF,PTS,year_start,year_end,position,height,weight,birth_date,college
name,,,,,,,,,,,,,,,,,,,,,
A.C. Green,1986.0,A.C. Green,PF,22.0,LAL,82.0,1.0,1542.0,11.8,0.564,...,99.0,229.0,521.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University
A.C. Green,1987.0,A.C. Green,PF,23.0,LAL,79.0,72.0,2240.0,15.7,0.599,...,102.0,171.0,852.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University
A.C. Green,1988.0,A.C. Green,PF,24.0,LAL,82.0,64.0,2636.0,14.5,0.581,...,120.0,204.0,937.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University
A.C. Green,1989.0,A.C. Green,PF,25.0,LAL,82.0,82.0,2510.0,17.8,0.594,...,119.0,172.0,1088.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University
A.C. Green,1990.0,A.C. Green,PF,26.0,LAL,82.0,82.0,2709.0,14.7,0.548,...,116.0,207.0,1061.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University

In [13]:
df_merge['YearInNBA'] = df_merge.Year - df_merge.year_start

In [14]:
df_merge.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,PF,PTS,year_start,year_end,position,height,weight,birth_date,college,YearInNBA
name,,,,,,,,,,,,,,,,,,,,,
A.C. Green,1986.0,A.C. Green,PF,22.0,LAL,82.0,1.0,1542.0,11.8,0.564,...,229.0,521.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University,0.0
A.C. Green,1987.0,A.C. Green,PF,23.0,LAL,79.0,72.0,2240.0,15.7,0.599,...,171.0,852.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University,1.0
A.C. Green,1988.0,A.C. Green,PF,24.0,LAL,82.0,64.0,2636.0,14.5,0.581,...,204.0,937.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University,2.0
A.C. Green,1989.0,A.C. Green,PF,25.0,LAL,82.0,82.0,2510.0,17.8,0.594,...,172.0,1088.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University,3.0
A.C. Green,1990.0,A.C. Green,PF,26.0,LAL,82.0,82.0,2709.0,14.7,0.548,...,207.0,1061.0,1986.0,2001.0,F-C,6-9,220.0,"October 4, 1963",Oregon State University,4.0

In [15]:
df_merge.groupby('name').PTS.max()

name
A.C. Green            1204.0
A.J. Bramlett            8.0
A.J. English           886.0
A.J. Guyton            244.0
A.J. Hammons            48.0
A.J. Price             441.0
A.J. Wynder             12.0
A.W. Holt                4.0
Aaron Brooks          1604.0
Aaron Gordon          1019.0
Aaron Gray             262.0
Aaron Harrison          18.0
Aaron James            973.0
Aaron McKie            878.0
Aaron Miles             16.0
Aaron Swinson           24.0
Aaron Williams         838.0
Abdul Jeelani          737.0
Acie Earl              410.0
Acie Law               235.0
Adam Harrington         30.0
Adam Keefe             620.0
Adam Morrison          917.0
Adonal Foyle           440.0
Adonis Jordan           15.0
Adonis Thomas           14.0
Adreian Payne          213.0
Adrian Branch          498.0
Adrian Caldwell        110.0
Adrian Dantley*       2457.0
                       ...
Worthy Patterson         7.0
Xavier Henry           432.0
Xavier McDaniel       1890.0
Xavier Munford          80.0
Xavier Silas            11.0
Yakhouba Diawara       284.0
Yao Ming*             1514.0
Yaroslav Korolev        27.0
Yi Jianlian            623.0
Yinka Dare             164.0
Yogi Ferrell           462.0
York Larese            302.0
Yuta Tabuse              7.0
Yvon Joseph              2.0
Zabian Dowdell         121.0
Zach LaVine           1150.0
Zach Randolph         1681.0
Zaid Abdul-Aziz        865.0
Zan Tabak              514.0
Zarko Cabarkapa        238.0
Zarko Paspalj           72.0
Zaza Pachulia          911.0
Zeke Sinicola           11.0
Zeke Zawoluk           592.0
Zeljko Rebraca         513.0
Zelmo Beaty*          1733.0
Zendon Hamilton        324.0
Zoran Dragic            28.0
Zoran Planinic         217.0
Zydrunas Ilgauskas    1390.0
Name: PTS, Length: 3921, dtype: float64

In [16]:
mydf = df_merge[df_merge.Player.isin(players_studied)]

In [17]:
mydf['PPG'] = mydf.PTS/mydf.G

/Users/rami/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [74]:
import math
values = {}
for index, college in mydf['college'].items():
    if str(college) == 'nan':  
        values[index] = False
    else:
        values[index] = True

In [77]:
mydf['wentToCollege'] = mydf['Player'].apply(lambda x: values[x])

/Users/rami/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [79]:
mydf.to_csv('data.csv')

In [78]:
mydf

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,year_start,year_end,position,height,weight,birth_date,college,YearInNBA,PPG,wentToCollege
name,,,,,,,,,,,,,,,,,,,,,
Dwyane Wade,2004.0,Dwyane Wade,PG,22.0,MIA,61.0,56.0,2126.0,17.6,0.530,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,0.0,16.245902,True
Dwyane Wade,2005.0,Dwyane Wade,SG,23.0,MIA,77.0,77.0,2974.0,23.1,0.561,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,1.0,24.077922,True
Dwyane Wade,2006.0,Dwyane Wade,SG,24.0,MIA,75.0,75.0,2892.0,27.6,0.577,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,2.0,27.200000,True
Dwyane Wade,2007.0,Dwyane Wade,SG,25.0,MIA,51.0,50.0,1931.0,28.9,0.583,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,3.0,27.392157,True
Dwyane Wade,2008.0,Dwyane Wade,SG,26.0,MIA,51.0,49.0,1954.0,21.5,0.549,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,4.0,24.588235,True
Dwyane Wade,2009.0,Dwyane Wade,SG,27.0,MIA,79.0,79.0,3048.0,30.4,0.574,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,5.0,30.202532,True
Dwyane Wade,2010.0,Dwyane Wade,SG,28.0,MIA,77.0,77.0,2792.0,28.0,0.562,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,6.0,26.558442,True
Dwyane Wade,2011.0,Dwyane Wade,SG,29.0,MIA,76.0,76.0,2823.0,25.6,0.581,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,7.0,25.539474,True
Dwyane Wade,2012.0,Dwyane Wade,SG,30.0,MIA,49.0,49.0,1625.0,26.3,0.559,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,8.0,22.081633,True
Dwyane Wade,2013.0,Dwyane Wade,SG,31.0,MIA,69.0,69.0,2391.0,24.0,0.571,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,9.0,21.202899,True
Dwyane Wade,2014.0,Dwyane Wade,SG,32.0,MIA,54.0,53.0,1775.0,22.0,0.588,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,10.0,19.037037,True
Dwyane Wade,2015.0,Dwyane Wade,SG,33.0,MIA,62.0,62.0,1971.0,21.4,0.534,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,11.0,21.467742,True
Dwyane Wade,2016.0,Dwyane Wade,SG,34.0,MIA,74.0,73.0,2258.0,20.3,0.517,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,12.0,19.040541,True
Dwyane Wade,2017.0,Dwyane Wade,SG,35.0,CHI,60.0,59.0,1792.0,18.5,0.508,...,2004.0,2018.0,G,6-4,220.0,"January 17, 1982",Marquette University,13.0,18.266667,True
Kevin Durant,2008.0,Kevin Durant,SG,19.0,SEA,80.0,80.0,2768.0,15.8,0.519,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,0.0,20.300000,True
Kevin Durant,2009.0,Kevin Durant,SF,20.0,OKC,74.0,74.0,2885.0,20.8,0.577,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,1.0,25.283784,True
Kevin Durant,2010.0,Kevin Durant,SF,21.0,OKC,82.0,82.0,3239.0,26.2,0.607,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,2.0,30.146341,True
Kevin Durant,2011.0,Kevin Durant,SF,22.0,OKC,78.0,78.0,3038.0,23.6,0.589,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,3.0,27.705128,True
Kevin Durant,2012.0,Kevin Durant,SF,23.0,OKC,66.0,66.0,2546.0,26.2,0.610,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,4.0,28.030303,True
Kevin Durant,2013.0,Kevin Durant,SF,24.0,OKC,81.0,81.0,3119.0,28.3,0.647,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,5.0,28.148148,True
Kevin Durant,2014.0,Kevin Durant,SF,25.0,OKC,81.0,81.0,3122.0,29.8,0.635,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,6.0,32.012346,True
Kevin Durant,2015.0,Kevin Durant,SF,26.0,OKC,27.0,27.0,913.0,27.6,0.633,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,7.0,25.407407,True
Kevin Durant,2016.0,Kevin Durant,SF,27.0,OKC,72.0,72.0,2578.0,28.2,0.634,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,8.0,28.180556,True
Kevin Durant,2017.0,Kevin Durant,SF,28.0,GSW,62.0,62.0,2070.0,27.6,0.651,...,2008.0,2018.0,F-G,6-9,240.0,"September 29, 1988",University of Texas at Austin,9.0,25.080645,True
Kevin Garnett,1996.0,Kevin Garnett,SF,19.0,MIN,80.0,43.0,2293.0,15.8,0.522,...,1996.0,2016.0,F-C,6-11,240.0,"May 19, 1976",NaN,0.0,10.437500,False
Kevin Garnett,1997.0,Kevin Garnett,SF,20.0,MIN,77.0,77.0,2995.0,18.2,0.537,...,1996.0,2016.0,F-C,6-11,240.0,"May 19, 1976",NaN,1.0,17.000000,False
Kevin Garnett,1998.0,Kevin Garnett,PF,21.0,MIN,82.0,82.0,3222.0,20.4,0.527,...,1996.0,2016.0,F-C,6-11,240.0,"May 19, 1976",NaN,2.0,18.512195,False
Kevin Garnett,1999.0,Kevin Garnett,PF,22.0,MIN,47.0,47.0,1780.0,22.4,0.493,...,1996.0,2016.0,F-C,6-11,240.0,"May 19, 1976",NaN,3.0,20.787234,False
Kevin Garnett,2000.0,Kevin Garnett,PF,23.0,MIN,81.0,81.0,3243.0,23.6,0.545,...,1996.0,2016.0,F-C,6-11,240.0,"May 19, 1976",NaN,4.0,22.925926,False
Kevin Garnett,2001.0,Kevin Garnett,PF,24.0,MIN,81.0,81.0,3202.0,23.9,0.531,...,1996.0,2016.0,F-C,6-11,240.0,"May 19, 1976",NaN,5.0,22.024691,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tracy McGrady,2008.0,Tracy McGrady,SG,28.0,HOU,66.0,62.0,2440.0,18.4,0.487,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,10.0,21.621212,False
Tracy McGrady,2009.0,Tracy McGrady,SG,29.0,HOU,35.0,35.0,1181.0,16.3,0.492,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,11.0,15.571429,False
Tracy McGrady,2010.0,Tracy McGrady,SG,30.0,TOT,30.0,24.0,673.0,12.2,0.466,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,12.0,8.166667,False
Tracy McGrady,2010.0,Tracy McGrady,SG,30.0,HOU,6.0,0.0,46.0,12.4,0.439,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,12.0,3.166667,False
Tracy McGrady,2010.0,Tracy McGrady,SG,30.0,NYK,24.0,24.0,627.0,12.2,0.469,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,12.0,9.416667,False
Tracy McGrady,2011.0,Tracy McGrady,SG,31.0,DET,72.0,39.0,1686.0,14.9,0.503,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,13.0,7.972222,False
Tracy McGrady,2012.0,Tracy McGrady,SF,32.0,ATL,52.0,0.0,837.0,13.6,0.510,...,1998.0,2012.0,F-G,6-8,210.0,"May 24, 1979",NaN,14.0,5.250000,False
Vince Carter,1999.0,Vince Carter,SF,22.0,TOR,50.0,49.0,1760.0,19.6,0.516,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,0.0,18.260000,True
Vince Carter,2000.0,Vince Carter,SF,23.0,TOR,82.0,82.0,3126.0,23.4,0.543,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,1.0,25.695122,True
Vince Carter,2001.0,Vince Carter,SF,24.0,TOR,75.0,75.0,2979.0,25.0,0.551,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,2.0,27.600000,True
Vince Carter,2002.0,Vince Carter,SG,25.0,TOR,60.0,60.0,2385.0,20.5,0.515,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,3.0,24.733333,True
Vince Carter,2003.0,Vince Carter,SG,26.0,TOR,43.0,42.0,1471.0,21.9,0.532,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,4.0,20.558140,True
Vince Carter,2004.0,Vince Carter,SG,27.0,TOR,73.0,73.0,2785.0,20.0,0.501,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,5.0,22.534247,True
Vince Carter,2005.0,Vince Carter,SF-SG,28.0,TOT,77.0,76.0,2828.0,22.9,0.541,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,6.0,24.493506,True
Vince Carter,2005.0,Vince Carter,SG,28.0,TOR,20.0,20.0,608.0,17.0,0.475,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,6.0,15.850000,True
Vince Carter,2005.0,Vince Carter,SF,28.0,NJN,57.0,56.0,2220.0,24.5,0.556,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,6.0,27.526316,True
Vince Carter,2006.0,Vince Carter,SG,29.0,NJN,79.0,79.0,2906.0,21.6,0.536,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,7.0,24.189873,True
Vince Carter,2007.0,Vince Carter,SG,30.0,NJN,82.0,82.0,3126.0,21.8,0.559,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,8.0,25.243902,True
Vince Carter,2008.0,Vince Carter,SG,31.0,NJN,76.0,72.0,2959.0,18.8,0.550,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,9.0,21.342105,True
Vince Carter,2009.0,Vince Carter,SG,32.0,NJN,80.0,80.0,2946.0,19.3,0.545,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,10.0,20.775000,True
Vince Carter,2010.0,Vince Carter,SG,33.0,ORL,75.0,74.0,2310.0,17.1,0.541,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,11.0,16.586667,True
Vince Carter,2011.0,Vince Carter,SG,34.0,TOT,73.0,63.0,2051.0,14.8,0.528,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,12.0,14.000000,True
Vince Carter,2011.0,Vince Carter,SG,34.0,ORL,22.0,22.0,664.0,16.2,0.557,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,12.0,15.136364,True
Vince Carter,2011.0,Vince Carter,SG,34.0,PHO,51.0,41.0,1387.0,14.2,0.516,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,12.0,13.509804,True
Vince Carter,2012.0,Vince Carter,SG,35.0,DAL,61.0,40.0,1542.0,13.6,0.519,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,13.0,10.081967,True
Vince Carter,2013.0,Vince Carter,SF,36.0,DAL,81.0,3.0,2093.0,17.8,0.571,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,14.0,13.432099,True
Vince Carter,2014.0,Vince Carter,SG,37.0,DAL,81.0,0.0,1973.0,15.9,0.539,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,15.0,11.938272,True
Vince Carter,2015.0,Vince Carter,SG,38.0,MEM,66.0,1.0,1091.0,9.6,0.445,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,16.0,5.818182,True
Vince Carter,2016.0,Vince Carter,SG,39.0,MEM,60.0,3.0,1005.0,12.7,0.520,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,17.0,6.583333,True
Vince Carter,2017.0,Vince Carter,SF,40.0,MEM,73.0,15.0,1799.0,11.7,0.542,...,1999.0,2018.0,G-F,6-6,220.0,"January 26, 1977",University of North Carolina,18.0,8.027397,True